kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: api-feed
  name: api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: api-feed
  template:
    metadata:
      labels:
        k8s-app: api-feed
    spec:
      containers:
        - name: api-feed
          image: ralfrr/udacity_proj4_feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AWS_PROFILE  
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: JWT_SECRET  
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: URL
          volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret           