kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: backend-feed
  name: backend-feed
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: backend-feed
  type: ClusterIP