kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: frontend-udugram
  name: frontend-udugram
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    k8s-app: frontend-udugram
  type: LoadBalancer