kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: reverseproxy-proj4
  name: reverseproxy-proj4
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: reverseproxy-proj4
  template:
    metadata:
      labels:
        k8s-app: reverseproxy-proj4
    spec:
      containers:
        - name: reverseproxy-proj4
          image: ralfrr/udacity_proj4_reverseproxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP