apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy-proj4
  name: reverseproxy-proj4
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    k8s-app: reverseproxy-proj4
  type: LoadBalancer