kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: backend-user
  name: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: backend-user
  template:
    metadata:
      labels:
        k8s-app: backend-user
    spec:
      containers:
        - name: backend-user
          image: ralfrr/udacity_project4_user
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_PROFILE  
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET  
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: URL