kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: backend-user
  name: backend-user
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    k8s-app: backend-user
  type: ClusterIP